package org.mov.prefs;

import javax.swing.*;

/*
 * EquationPage.java
 *
 * Created on 24 January 2002, 23:43
 */

/**
 *
 * @author  Dan
 */
public class EquationPage extends javax.swing.JPanel implements PreferencesPage
{

    /** The desktop that new windows are opened upon */
    JDesktopPane desktop;
    
    /** Creates new form EquationPage */
    public EquationPage(JDesktopPane desktop) {
        initComponents();
        this.desktop = desktop;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        jSplitPane1 = new javax.swing.JSplitPane();
        listPanel = new javax.swing.JPanel();
        listScrollPane = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList();
        listButtonPanel = new javax.swing.JPanel();
        newButton = new javax.swing.JButton();
        editButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        entryPanel = new javax.swing.JPanel();
        namePanel = new javax.swing.JPanel();
        nameLabel = new javax.swing.JLabel();
        nameText = new javax.swing.JTextField();
        detailPanel = new javax.swing.JPanel();
        detailLabel = new javax.swing.JLabel();
        detailText = new javax.swing.JTextField();
        buttonPanel = new javax.swing.JPanel();
        okButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.X_AXIS));
        
        jSplitPane1.setContinuousLayout(true);
        jSplitPane1.setLastDividerLocation(-1);
        jSplitPane1.setOneTouchExpandable(true);
        listPanel.setLayout(new java.awt.GridBagLayout());
        java.awt.GridBagConstraints gridBagConstraints1;
        
        listScrollPane.setViewportView(jList2);
        
        gridBagConstraints1 = new java.awt.GridBagConstraints();
        gridBagConstraints1.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints1.weightx = 2.0;
        gridBagConstraints1.weighty = 2.0;
        listPanel.add(listScrollPane, gridBagConstraints1);
        
        listButtonPanel.setLayout(new java.awt.GridBagLayout());
        java.awt.GridBagConstraints gridBagConstraints2;
        
        newButton.setLabel("New...");
        gridBagConstraints2 = new java.awt.GridBagConstraints();
        listButtonPanel.add(newButton, gridBagConstraints2);
        
        editButton.setLabel("Edit...");
        gridBagConstraints2 = new java.awt.GridBagConstraints();
        listButtonPanel.add(editButton, gridBagConstraints2);
        
        deleteButton.setLabel("Delete");
        gridBagConstraints2 = new java.awt.GridBagConstraints();
        listButtonPanel.add(deleteButton, gridBagConstraints2);
        
        gridBagConstraints1 = new java.awt.GridBagConstraints();
        gridBagConstraints1.gridx = 0;
        gridBagConstraints1.gridy = 1;
        listPanel.add(listButtonPanel, gridBagConstraints1);
        
        jSplitPane1.setLeftComponent(listPanel);
        
        entryPanel.setLayout(new java.awt.GridBagLayout());
        java.awt.GridBagConstraints gridBagConstraints3;
        
        entryPanel.setBorder(new javax.swing.border.EtchedBorder());
        nameLabel.setText("Function name");
        nameLabel.setMaximumSize(new java.awt.Dimension(89, 16));
        nameLabel.setMinimumSize(new java.awt.Dimension(89, 16));
        nameLabel.setPreferredSize(new java.awt.Dimension(89, 16));
        namePanel.add(nameLabel);
        
        nameText.setMinimumSize(new java.awt.Dimension(100, 20));
        nameText.setPreferredSize(new java.awt.Dimension(100, 20));
        namePanel.add(nameText);
        
        gridBagConstraints3 = new java.awt.GridBagConstraints();
        entryPanel.add(namePanel, gridBagConstraints3);
        
        detailLabel.setText("Function details");
        detailPanel.add(detailLabel);
        
        detailText.setPreferredSize(new java.awt.Dimension(100, 20));
        detailPanel.add(detailText);
        
        gridBagConstraints3 = new java.awt.GridBagConstraints();
        gridBagConstraints3.gridx = 0;
        gridBagConstraints3.gridy = 1;
        gridBagConstraints3.insets = new java.awt.Insets(5, 5, 5, 5);
        entryPanel.add(detailPanel, gridBagConstraints3);
        
        okButton.setText("OK");
        buttonPanel.add(okButton);
        
        cancelButton.setText("Cancel");
        buttonPanel.add(cancelButton);
        
        gridBagConstraints3 = new java.awt.GridBagConstraints();
        gridBagConstraints3.gridx = 0;
        gridBagConstraints3.gridy = 2;
        entryPanel.add(buttonPanel, gridBagConstraints3);
        
        jSplitPane1.setRightComponent(entryPanel);
        
        add(jSplitPane1);
        
    }//GEN-END:initComponents

    /**
     * Update the preferences file.
     */
    public void save() {
    }    

    /**
     * Return displayed component for this page.
     *
     * @return the component to display.
     */
    public JComponent getComponent() {
        return this;
    }    

    /**
     * Return the window title.
     *
     * @return	the window title.
     */
    public String getTitle() {
        return "Functions preferences";
    }
    
    /**
     * Return menu bar for quote source preferences module.
     *
     * @return	the menu bar.
     */
    public JMenuBar getJMenuBar() {
        return null;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JPanel listPanel;
    private javax.swing.JScrollPane listScrollPane;
    private javax.swing.JList jList2;
    private javax.swing.JPanel listButtonPanel;
    private javax.swing.JButton newButton;
    private javax.swing.JButton editButton;
    private javax.swing.JButton deleteButton;
    private javax.swing.JPanel entryPanel;
    private javax.swing.JPanel namePanel;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField nameText;
    private javax.swing.JPanel detailPanel;
    private javax.swing.JLabel detailLabel;
    private javax.swing.JTextField detailText;
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JButton okButton;
    private javax.swing.JButton cancelButton;
    // End of variables declaration//GEN-END:variables

}
